### ISSUE TITLE
Restore publisher in ac table is missing

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1132]
When you toggle off publisher in the panel we should show restore option in the settings.

![screenshot_20190219-083408](https://user-images.githubusercontent.com/9574457/52998810-79e49000-3424-11e9-8d04-ec901519171d.png)

Desktop:
![image](https://user-images.githubusercontent.com/9574457/52998867-997bb880-3424-11e9-8d6f-94a5277bf9fe.png)

**Comment by ryanml** [comment]
Fixed via: https://github.com/brave/browser-android-tabs/commit/47a72d1b2e3201629d582639487b9e62e631dd32

**Comment by SergeyZhukovsky** [comment]
@ryanml I don't think it's done. We should show an option to restore a website for autocontribution.

**Comment by SergeyZhukovsky** [comment]
We have it again on a new version https://github.com/brave/browser-android-tabs/issues/1201, I check it myself and don't see any way on how to restore a website.

**Comment by SergeyZhukovsky** [comment]
@ryanml should the commit above ^ fix the issue? I still don't see any option to restore a website.

**Comment by ryanml** [comment]
@SergeyZhukovsky this is fully fixed as of: https://github.com/brave/browser-android-tabs/commit/2e2e351cfda11d62ada9a89cd5d43aa903b4124c

![screenshot_20190305-172140_brave - debug](https://user-images.githubusercontent.com/8732757/53847044-1d28bf80-3f64-11e9-8f40-613e65062589.jpg)

Note that retesting should be done with a clean start
