### ISSUE TITLE
Strange orange dot appears when refreshing web page

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-android-tabs#724]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
When refreshing the web page by pulling down and releasing, a solid orange dot appears and is displayed on top of the refresh icon/animation. Its worth noting that it seems to _only_ affect Android 9.0. Orange dot does not appear when the same actions are performed in Chrome.

**Device Details:**
   - Install Type(ARM, x86):
   - Device(Phone, Tablet, Phablet): Pixel 2 XL
   - Android Version: Android 9.0 (Pie)
    
**Brave Version:**
Live release: 1.0.54

**Steps to reproduce:**
[on an Android device running 9.0 Pie]
    1. Open Brave and navigate to any web page
    2. After the page loads, press, drag, and release browser window to trigger page refresh

**Actual Behavior**
Page gets refreshed
Refresh icon/animation appears
Orange dot shows up

**Expected Behavior**
Page is refreshed
Refresh icon/animation appears
Orange dot should **not** be present

**Is this an issue with Beta build?**
N/A

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes 

**Website problems only:**
  - did you check with Brave Shields down? <-----------Yes
  - did you check in Chrome for same behavior? <-----------Yes

**Screenshot if needed:**
![image](https://user-images.githubusercontent.com/3299098/44559409-c0b82e00-a6fe-11e8-9af5-1502d2dbb9d8.png)

**Comment by kjozwiak** [comment]
Example: https://youtu.be/z9gMGexq6qI

**Comment by LaurenWags** [comment]
multiple +1s from: https://community.brave.com/t/bug-refresh-icon-is-bugged-when-using-pull-to-refresh/30753

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/61e55a57b76bd716eec9cef655e3f92873a6bf86

**Comment by samartnik** [comment]
For QA: it's possible to check if you had device with the problem. In new version problem should disappear.

**Comment by R4P70R** [comment]
I want to point out that I'm still experiencing this bug in 1.0.57 with Pixel 2, Android pie

**Comment by kjozwiak** [comment]
@R4P70R thanks for the double check 👍I'm getting the same results as you with the following devices:

* `Brave 1.0.57 CR: 68.0.3440.91` on a Pixel 1 using android 9 - Reproduced
* `Brave 1.0.57 CR: 68.0.3440.91` on a Pixel 2 using android 9 - Reproduced

@srirambv @samartnik re-opening and moving this into https://github.com/brave/browser-android-tabs/milestone/52 as this still seems to be an issue. Reproduced by @R4P70R and myself.

**Comment by kjozwiak** [comment]
@SergeyZhukovsky can try getting this fixed in the next release? Shouldn't be hard and it's getting a lot of +1 from the community.

**Comment by Tikotik** [comment]
I just want to add, its kind of cute on my nougat device with small dot fiiting perfectly on one end on both refresh icon and drag refresh icon.

**Comment by jonathansampson** [comment]
This issue was brought up today [on Twitter](https://twitter.com/ChrisPirillo/status/1055551267143995392).

**Comment by Brave-Matt** [comment]
Just got another report of this still appearing:
![image](https://user-images.githubusercontent.com/3299098/47689457-3e893180-dba7-11e8-922c-06212226428f.png)

**Comment by kjozwiak** [comment]
@SergeyZhukovsky we should probably try getting this fixed in the next version. Seems like we're getting more complaints from the community. I don't think fixing this should take a lot of effort and should be an easy win.

**Comment by samartnik** [comment]
https://github.com/brave/browser-android-tabs/commit/19712a2f3327b5f069ef4a6159af483970b20d1e

**Comment by kjozwiak** [comment]
Verified using `1.0.61, CR: 70.0.3538.80` with a Pixel XL using `Android 9.0.0`. Example:

![screenshot_20181031-134615](https://user-images.githubusercontent.com/2602313/47807995-d146df00-dd13-11e8-9efd-78fbdce9e688.png)

Refreshed several different pages and didn't see the orange dot that was appearing before 👍
